# Generated by Django 4.1.2 on 2023-04-04 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0002_alter_player_options_alter_player_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
        migrations.AlterModelManagers(
            name='player',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='player',
            name='email',
        ),
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='player',
            name='username',
        ),
    ]
