# Generated by Django 4.1.2 on 2023-04-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0009_party_url_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='url_image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
