# Generated by Django 4.1.2 on 2023-04-27 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0010_player_url_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='who_ask',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ask', to=settings.AUTH_USER_MODEL),
        ),
    ]
