# Generated by Django 4.1.2 on 2023-07-11 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0012_message'),
    ]

    operations = [   
        migrations.AddField(
            model_name='party',
            name='type',
            field=models.CharField(max_length=500, null=True),
        ),
        
    ]
