# Generated by Django 4.1.2 on 2023-07-12 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0013_participant_tag_player_party_start_party_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='type',
            new_name='language',
        ),
        migrations.CreateModel(
            name='ArgumentParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('value', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=500)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_game_argument', to='server_api.party')),
            ],
        ),
    ]
