# Generated by Django 4.1.2 on 2023-07-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0014_rename_type_party_language_argumentparty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='start',
        ),
    ]
