# Generated by Django 4.1.2 on 2023-07-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0015_remove_party_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='point',
            field=models.IntegerField(null=True),
        ),
    ]
