# Generated by Django 4.1.2 on 2023-07-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0016_participant_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(db_collation='utf8mb4_general_ci'),
        ),
    ]
