# Generated by Django 4.1.2 on 2023-07-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0017_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='max_player',
            field=models.IntegerField(null=True),
        ),
    ]
